### ISSUE TITLE
TypeError Filament\Forms\Components\Repeater::Filament\Forms\Components{closure}(): Argument #1 ($state) must be of type array, null given

### ISSUE THREAD

**Issue by giorgiopogliani** [laravel-filament/filament#1055]
### Package

filament/forms

### Package Version

v2.7.4

### Laravel Version

8.77.1

### Livewire Version

2.8.2

### PHP Version

8.0

### Bug description

A resource with that has a form with a repeater inside a builder gives the following error on save: 
TypeError

```
Type Error
Filament\Forms\Components\Repeater::Filament\Forms\Components{closure}(): 
Argument #1 ($state) must be of type array, null given, called in
[...]/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 36
```

### Steps to reproduce

Create a resource with the following form as example: 
```php
return Builder::make('content')
    ->blocks([
        Builder\Block::make('pricing')
            ->schema([
                Placeholder::make('Pricing'),
                TextInput::make('title')->required(),
                Repeater::make('plans')->schema([
                    TextInput::make('title')->required()
                ])
            ]),
    ]);
```

On save you will see the error. The same repeater outside the builder block works fine.

**Comment by danharrin** [comment]
Fixed by #1061.

**Comment by giorgiopogliani** [comment]
I actually still have the error, it looks like that for some reason the state variable here is null and so it gives type error later on. 

https://github.com/laravel-filament/filament/blob/4167b938ea23387f6c9c136b1619279917c7abeb/packages/forms/src/Components/Concerns/HasState.php#L125-L130


during this callback:
https://github.com/laravel-filament/filament/blob/4167b938ea23387f6c9c136b1619279917c7abeb/packages/forms/src/Components/Repeater.php#L126-L128

**Comment by danharrin** [comment]
Is this for edit or create?

**Comment by giorgiopogliani** [comment]
This happens both in edit and in create.

**Comment by danharrin** [comment]
> This happens both in edit and in create.

How about on the latest version?

**Comment by giorgiopogliani** [comment]
Now the error changed to `ErrorException
Undefined array key "type"`. In one of my attempts I tried to add a `?? []` too and I got this same error. For some reason in the database the type key is missing. This is what get saved: 
```json
{ "43deba34-5f7b-4b00-8b1a-3d7a89ad686a": {"data": {"plans": []} }
```
Besides the error the content is not even actually saved because it arrives still null and fallback to the empty array. I think there must be something to fix up in the chain.

Maybe somewhere around here but I can't really understand the code:
https://github.com/laravel-filament/filament/blob/880d201732edfaa2f6353d402d576e735f2058da/packages/forms/src/Concerns/HasState.php#L67-L98
 
Thanks!

**Comment by giorgiopogliani** [comment]
I looked a bit more the content that get saved and with only one text block and one pricing block, the pricing block has the repeater plans this is what get saved. Plans is multiplied... ?
```json
{
  "0": {
    "data": {
      "title": "adas",
      "content": "asda"
    },
    "type": "text"
  },
  "1": {
    "data": {
      "plans": [
        
      ],
      "title": "asds",
      "content": "asdas"
    },
    "type": "pricing"
  },
  "2": {
    "data": {
      "plans": [
        
      ]
    }
  },
  "3": {
    "data": {
      "plans": [
        
      ]
    }
  },
  "4": {
    "data": {
      "plans": [
        
      ]
    }
  },
  "5": {
    "data": {
      "plans": [
        
      ]
    }
  },
  "17cea4b8-3e7e-4846-90e0-07b52cdd3bde": {
    "data": {
      "plans": [
        
      ]
    }
  }
}
```

**Comment by danharrin** [comment]
You're using the forms package without the admin panel, correct? Could you send me a full Livewire component that I can copy and replicate this myself please. Try to avoid any external classes or other dependencies. Thanks

**Comment by giorgiopogliani** [comment]
No, I am using it with the admin panel.

**Comment by danharrin** [comment]
Okay, can I have the following then, please:
- Resource class
- Database migration
- Model
- Database seeder (and factories if required) for existing data

**Comment by giorgiopogliani** [comment]
You should find everything here, if I can help in some other ways let me know!
[test.zip](https://github.com/laravel-filament/filament/files/7796466/test.zip)

I don't have factories. You might need to install `spatie/laravel-sluggable`, I used it on the model.

**Comment by danharrin** [comment]
Thanks. This should be fixed in the latest version, but I'm not gonna close this issue until you confirm that.

Here's a test array from your builder now:

<img width="462" alt="Screenshot 2022-01-01 at 13 41 07" src="https://user-images.githubusercontent.com/41773797/147851920-71bd7e83-1ac2-4a8b-a61f-26e33e48b409.png">

**Comment by giorgiopogliani** [comment]
I updated everything now `filament/forms` is at `2.7.15` but I still have the error `ErrorException Undefined array key "type"`

This is what I find in the database:

```json
[
  {
    "data": {
      "plans": [
        {
          "title": "asdasd"
        },
        {
          "title": "asdasd"
        }
      ],
      "title": "asdas"
    },
    "type": "pricing"
  },
  {
    "data": {
      "plans": [
        
      ]
    }
  },
  {
    "data": {
      "plans": [
        
      ]
    }
  },
  {
    "data": {
      "plans": [
        
      ]
    }
  },
  {
    "data": {
      "plans": [
        
      ]
    }
  }
]
```

It has the data now, but there are ghosts data plans outside the pricing block without the type key. It seems that the Group and the Card block are messing with the component (state path?) because I tried to remove the Cards and Blocks and the number of ghosts decreased.

**Comment by danharrin** [comment]
Can you remove all content from that database field as it's saved corrupt data from a previous version (I think).

**Comment by giorgiopogliani** [comment]
I did, multiple times, and it gives that result. Both on create and edit.

**Comment by danharrin** [comment]
> I did, multiple times, and it gives that result. Both on create and edit.

Thanks for clarifying. I was testing with the builder field (and its child components) only, so I didn't catch the bug with the nested cards and grid.

Now, I'm pretty sure that this has all been fixed now. Let me know if not.

**Comment by giorgiopogliani** [comment]
Now it works 🎉 Thanks!
