### ISSUE TITLE
Money Input Mask Empty When Zero

### ISSUE THREAD

**Issue by intrepidws** [laravel-filament/filament#1553]
### Package

filament/filament

### Package Version

v2.10.6

### Laravel Version

v8.83.0

### Livewire Version

v2.10.1

### PHP Version

PHP 8.0.13

### Bug description

When using the `money` input mask on a TextInput field with a value of zero - only `$` is displayed instead of `$0.00`.

### Steps to reproduce

My form schema has the following:

```
Forms\Components\TextInput::make('amount')
    ->mask(fn (Forms\Components\TextInput\Mask $mask) => $mask->money('$', ',', 2)),
```

For a field with a value of zero, this displays only `$` when I would expect that it should show `$0.00`.

**Comment by ryangjchandler** [comment]
@intrepidws Is this still a problem since https://github.com/laravel-filament/filament/pull/1533 has been merged in?

**Comment by danharrin** [comment]
Hm, I think this is just an iMask bug. We pass `->lazyPlaceholder(false)` which should fix this, but it doesn't.

**Comment by intrepidws** [comment]
> @intrepidws Is this still a problem since #1533 has been merged in?

@ryangjchandler Yes I tested this on v2.10.6, which had #1533 merged.

Just to be certain, I upgraded to the recently released v2.10.7 and can confirm the problem still exists. I'll look into filing a bug report with iMask.

**Comment by intrepidws** [comment]
@danharrin I'm sure that I've simplified the implementation too much or missed something obvious but I just made a CodePen with iMask that seems to work fine with a zero value.

https://codepen.io/intrepidws/pen/zYPzWdK

**Comment by ryangjchandler** [comment]
I wonder if it's something to do with the configuration that the `Mask::money` method creates. Perhaps the normalise zeroes?

Will have to debug & dig into it at some point this weekend. @danharrin

**Comment by intrepidws** [comment]
That pen should (at least to the best that I can tell) utilize all of the same iMask config that the `Mask::money` method creates.

**Comment by danharrin** [comment]
Could you maybe try converting it to Alpine (using our code in text-input.js) and see if that still works?

**Comment by intrepidws** [comment]
So I'm a little out of my element here, but from what I can [these lines](https://github.com/laravel-filament/filament/blob/d93c9fe3b8b26074eeca28a3e934eba803ccac26/packages/forms/resources/js/components/text-input.js#L18-L20) are meant to assign the value when there is one. But there are two issues here:

1. The value of `this.state` coming in from a field with a zero value is actually `null` for some reason.
2. Even if the value of `this.state` _was_ zero, I don't believe that it would pass `if (this.state) {`

**Comment by tangjh** [comment]
I came across this issue.  Didn't manage to find what's wrong but did a workaround with the follow:

                                            ->afterStateHydrated(function (TextInput $component, $state) {
                                                if ($state == null) $component->state('0');
                                            })

If the value is non-zero and user delete the value, it will display 0.
However, if the value is already 0 and user delete the 0, it will stay empty.  I think this make sense as the value is 0 already and if user wants to clear the 0, means user doesn't want the 0.

**Comment by intrepidws** [comment]
@tangjh While I still think that a fix is needed here, your solution does work for my purposes, thanks. What is weird though is that `$state == null` works while `is_null($state)` does not.

**Comment by danharrin** [comment]
What is `$state` though? Is it null? or is it just a falsy value that could be triggered by an `==`

**Comment by intrepidws** [comment]
@danharrin Yea, I should've checked that - you're absolutely right. It's actually zero, so it's just a falsy value. So basically, forcing it to be a string of zero bypasses the problem I outlined in https://github.com/laravel-filament/filament/issues/1553#issuecomment-1039046729.

**Comment by ryangjchandler** [comment]
Ah, that classic `'0'` is a truthy value in JS but not in PHP.

**Comment by danharrin** [comment]
I think there is little we can do about this from our end tbh, except recommend that people set a default. What do you think about closing this issue?

**Comment by intrepidws** [comment]
It still feels like there is a bug somewhere to me but I'm not sure I'm smart enough to find it unfortunately. In the JS at [these lines](https://github.com/laravel-filament/filament/blob/d93c9fe3b8b26074eeca28a3e934eba803ccac26/packages/forms/resources/js/components/text-input.js#L18-L20), the value of `this.state` coming in from a field with a zero value is actually `null` for some reason - and that feels like a bug to me but I'm not sure.

**Comment by danharrin** [comment]
I don't know what the fix for that would be though - if you have any ideas then please reply them here or submit a PR. For now - a default value should work just fine I think.
