### ISSUE TITLE
Column manager disappears off top of screen when using relation manager

### ISSUE THREAD

**Issue by cannycookie** [laravel-filament/filament#17643]
### Package

filament/filament

### Package Version

v4.0.6

### Laravel Version

v12.27.1

### Livewire Version

v.3.6.4

### PHP Version

php 8.2

### Problem description

When using a relation manager and clicking the column manager the pop up menu disappears off the top of the screen and we can't scroll it into view.  Unable to see or click hidden check boxes.

<img width="1391" height="663" alt="Image" src="https://github.com/user-attachments/assets/4d9a6314-6908-4813-a08c-6226eb1b008b" />

### Expected behavior

if the popup menu is taller than the screen the page should scroll.

### Steps to reproduce

Seed the demo 
```php artisan db:seed```

Edit a user and click the column manager on Posts Relation manager

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/cannycookie/filament-bug-demo1

### Relevant log output

```shell

```

**Comment by nettsite** [comment]
This may be relevant to mention here: all the columns are listed in the column manager, including those which are not toggleable. That does tend to expand the column manager quite a bit sometimes, pushing it off the screen.

**Comment by cannycookie** [comment]
@nettsite good point, but still a problem, on my mac if there are rows in the table the column manager does switch to displaying from top down and scrolling down the page is possible but on a windows machine this doesn't happen so they can't access.

**Comment by archilex** [comment]
> This may be relevant to mention here: all the columns are listed in the column manager, including those which are not toggleable. That does tend to expand the column manager quite a bit sometimes, pushing it off the screen.

@danharrin Regarding the above, should we go ahead and hide non-toggleable columns when reordeable columns isn't enabled? With column groups it'd work similarly to what I implemented with null labels.

**Comment by danharrin** [comment]
Do you think that would be better? I do quite like being able to see the full list of columns to know where the new column will appear relatively.

The issue in this PR would still happen if reorderable columns is enabled, so I think the main priority is to fix the dropdown position or add some sort of max height & scrolling behaviour to the content.

**Comment by archilex** [comment]
Not sure if hiding non-toggleable columns would be necessarily better, but it is a change from v3. I can see how some may prefer to see the full list for context, and others not. If you would like me to make that configurable I could do that.

Back to this specific issue, `->columnManagerMaxHeight()` already exists and mitigates this a little, but ultimately this dropdown positioning is an ongoing issue that has affected the column and filter dropdowns since v3 where when 1) the dropdown is taller than the space between the dropdown and the bottom of the page (and thus can flip) and 2) the space between the dropdown and the bottom of the page is less than the space between the dropdown and the top of the page, then the dropdown will flip up and be cut off.

It might be an underlying issue with floating-ui? Maybe @awcodes has some insight here?

**Comment by nettsite** [comment]
It would be useful in most of my use cases to be able to not show the non-toggleable columns somehow, as with V3 behaviour. 

Having said that, I didn't even know about the column reordering, you guys are legend.

**Comment by awcodes** [comment]
As far as the screen clipping, I don't think there's a bullet proof way to solve this. As Dan said the best solution would be a max height and an overflow scroll. Ie, the height of the content is what it is. There's no way to force that into the bounding context of the browser viewport, especially with an absolute (teleported) element.

**Comment by archilex** [comment]
@danharrin Due to @awcodes comment, my suggestion would be we set `:flip=false` on both the column manager dropdown and the filter dropdown. This fixes this issue as well as provides a more consistent UI. It's always felt off to me when these dropdown flip up even when they do fit on the screen. If you agree I can submit a PR for this.

**Comment by danharrin** [comment]
In the demo, the dropdowns don't flip up for me unless there isn't enough room at the bottom of the browser window, do you see something different?

<img width="1472" height="906" alt="Image" src="https://github.com/user-attachments/assets/660a0dc5-83bf-4674-ad6b-8e731319b264" />

**Comment by archilex** [comment]
Correct, but if you have multiple widgets that push the table down, or the table is in a relation manager then there can easily be more room above the table than below it which is what triggers the flip.  Some users also zoom their browsers which, in combination with widgets,forms,RMs makes the available space below even less.

**Comment by danharrin** [comment]
Is there a way to make it prioritise positioning below if it can fit, even if there is more space above? That would be ideal

**Comment by archilex** [comment]
While I agree it would be good to prioritize maintaining it below if there is space (although potentially not possible given awcodes comment above), that wouldn’t solve the main issue that it shouldn’t flip up if there isn’t enough space above. When it’s below it won’t clip as the page becomes scrollable. If it flips up and there isn’t enough space it clips making everything in the dropdown above the page inaccessible.

**Comment by cannycookie** [comment]
@archilex  A long column manager does force the page to scroll on V3. Can you suggest a workaround - i can't update our live system until this works :-(

**Comment by cannycookie** [comment]
I made a js workaround that increases body min height as needed when the column manager opens and restores it when closed.  Could be done more elegantly in the column-manager.blade.php but  the below just needs adding as JS without modifying the core template.

```JS
document.addEventListener('DOMContentLoaded', () => {
    let originalBodyMinHeight = null;
    let expandedTo = null; // number we grew to (so we know when to restore)

    const SELECTORS = {
        triggerWrap: '.fi-dropdown-trigger', // has aria-expanded
        triggerBtn:
            '.fi-ta-col-manager-dropdown .fi-dropdown-trigger button,' +
            '[aria-label="Column manager"],[title="Column manager"]',
        panel: '.fi-dropdown-panel[style*="display: block"], .fi-dropdown-panel[aria-hidden="false"]',
        manager: '.fi-ta-col-manager',
    };

    const getOpenPanel = () => document.querySelector(SELECTORS.panel);

    const isManagerOpen = () => {
        const panel = getOpenPanel();
        return panel ? !!panel.querySelector(SELECTORS.manager) : false;
    };

    const saveOriginalMinHeight = () => {
        if (originalBodyMinHeight === null) {
            originalBodyMinHeight = document.body.style.minHeight || '';
        }
    };

    const expandIfNeeded = () => {
        const panel = getOpenPanel();
        if (!panel || !panel.querySelector(SELECTORS.manager)) return;

        const rect = panel.getBoundingClientRect();
        const padding = 60;

        // Where the panel's bottom sits in the document (no scrolling applied)
        const absBottom = window.scrollY + rect.bottom;
        const neededDocHeight = absBottom + padding;

        const currentDocHeight = Math.max(
            document.documentElement.scrollHeight,
            document.body.scrollHeight
        );

        if (neededDocHeight > currentDocHeight) {
            saveOriginalMinHeight();
            document.body.style.minHeight = `${neededDocHeight}px`;
            expandedTo = neededDocHeight;
        }
    };

    const restoreMinHeight = () => {
        if (expandedTo !== null) {
            document.body.style.minHeight = originalBodyMinHeight ?? '';
            originalBodyMinHeight = null;
            expandedTo = null;
        }
    };

    // Decide expand/restore after Alpine has toggled the dropdown.
    const ensurePanelStateFromTrigger = (wrapEl) => {
        // Alpine toggles on mousedown; wait a tick + layout
        setTimeout(() => {
            requestAnimationFrame(() => {
                requestAnimationFrame(() => {
                    const expanded = wrapEl?.getAttribute('aria-expanded') === 'true';
                    if (expanded) {
                        expandIfNeeded();
                    } else {
                        // Only restore if it’s actually closed (avoid fighting transitions)
                        if (!isManagerOpen()) restoreMinHeight();
                    }
                });
            });
        }, 0);
    };

    // Mouse users (Alpine binds x-on:mousedown on the wrapper)
    document.addEventListener('mousedown', (e) => {
        const wrap = e.target.closest(SELECTORS.triggerWrap);
        if (!wrap) return;
        ensurePanelStateFromTrigger(wrap);
    });

    // Keyboard users (Enter/Space -> click on the button)
    document.addEventListener('click', (e) => {
        const btn = e.target.closest(SELECTORS.triggerBtn);
        if (!btn) return;
        const wrap = btn.closest(SELECTORS.triggerWrap);
        if (wrap) ensurePanelStateFromTrigger(wrap);
    });

    // Clicks outside → if closed, restore
    document.addEventListener('click', (e) => {
        if (e.target.closest(SELECTORS.manager) || e.target.closest(SELECTORS.triggerWrap)) return;
        if (!isManagerOpen()) restoreMinHeight();
    });

    // Escape → restore
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') restoreMinHeight();
    });

    // Resize: if open, re-measure; if closed, restore (debounced)
    {
        let t;
        window.addEventListener('resize', () => {
            clearTimeout(t);
            t = setTimeout(() => {
                if (isManagerOpen()) {
                    // Re-expand to new size if needed
                    requestAnimationFrame(() => requestAnimationFrame(expandIfNeeded));
                } else {
                    restoreMinHeight();
                }
            }, 120);
        });
    }
});
```

**Comment by archilex** [comment]
@cannycookie I submitted a PR based on my solution above and we'll see what Dan says.

**Comment by cannycookie** [comment]
@archilex awesome thank you.   Hopefully that will solve it.   Do you know if it will fix the same issue with the table Action Groups being cut off when dropping down at the bottom of the page? : https://github.com/filamentphp/filament/issues/17639
