### ISSUE TITLE
Component visibility unaffected when using 'when()' on first reload

### ISSUE THREAD

**Issue by ciamarro** [laravel-filament/filament#312]
**Describe the bug**
Component not visible when result of `->when()`  is `true `when using a `->dependable()` field in 1.8.x.  
Problem did not exist on 1.7.5

**To reproduce**
Check 'medical_conditions' checkbox
```
//added to make sure it was not this
protected $casts = [
       'medical_conditions' => 'boolean',
       'behaviour' => 'boolean'
];
```
```
Components\Grid::make([
    Components\Checkbox::make('medical_conditions')->dependable(),
    Components\Textarea::make('medical_conditions_explain')->when(fn($record) => $record->medical_conditions == true),
])->columns(1),

//---Some more code

Components\Grid::make([
    Components\Checkbox::make('behaviour')->dependable(),
    Components\Textarea::make('behaviour_explain')->when(fn($record) => $record->behaviour == true),
])->columns(1),

//i tried !(empty()), 'true', 1, etc...
```

If I click on `behaviour`,  it triggers a reload, the `medical_conditions_explain` will finally show, but now the `behaviour_explain` will not.  It seems `$record` is one step _behind_

The `medical_conditions_explain` field is visible if `medical_conditions` was loaded as `TRUE` from the DB, however, unchecking `medical_conditions` has no effect on the visibility of `medical_conditions_explain`, so it remains visible

**Expected behavior**
Expect `medical_conditions_explain` to be visible when `medical_conditions` is checked, and not visible when unchecked.
Just to reiterate, all seemed to work in 1.7

**Context**
- Package version: 1.8.3
- Livewire version: 2.4.1
- Laravel version: 8.35.1
- Browser: Chrome
- Server OS: Ubuntu
- PHP version: 8
- Database: MySql 8

**Comment by ciamarro** [comment]
This seems only to be happening on EditRecord

**Comment by ciamarro** [comment]
Video
https://user-images.githubusercontent.com/2736722/113347066-a2792c80-9302-11eb-8024-cb8c42cc24a9.mp4

**Comment by YassinoB** [comment]
Same problem on EditRecord, it happens with me when using two select list using the dependable()

**Comment by danharrin** [comment]
Fixed by #341.

**Comment by ciamarro** [comment]
Sorry to reopen this but still an issue on EditRecord for me

https://user-images.githubusercontent.com/2736722/115247434-c86d4200-a0f4-11eb-9f36-68707629b48f.mp4
