### ISSUE TITLE
Issue with media upload in Relation Managers

### ISSUE THREAD

**Issue by nocodelab** [laravel-filament/filament#6128]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

2.17.*

### Laravel Version

10.0

### PHP Version

8.1

### Problem description

Hello guys, 
I was using the latest version of the package (2.17.*) and image upload fails while adding the SpatieMediaLibraryFileUpload in the Relation Manager form.
In normal Resources form everything works smoothly.

Downgrading to the 2.16.* is a temporary workaround.

### Expected behavior

Media file should be correctly associated with the model.

### Steps to reproduce

Just install the 2.17.* version of the package.

### Reproduction repository

https://bitbucket.org/giuseppemastrodonato/workspace/snippets/nEn8Ed

**Comment by zepfietje** [comment]
Thanks for reporting, @nocodelab! I've reopened the issue as you did in fact include some reproduction code. 😄

**Comment by agentphoenix** [comment]
I started having the same issue today. I did a little digging and it appears that there's a UUID mismatch happening.

After creating the media record, it returns the UUID, but that doesn't match what the record passed in to `deleteAbandonedFiles` has for its UUID. Since they don't match, it identifies the media record as abandoned and deletes the record out of the media table. I'm still digging into this, but figured I'd give some more context from what I've found so far.

**Comment by Yo1L** [comment]
Same here, uploaded file on create are deleted. When editing, it works just fine !
Downgrading to 2.16, just fix it...

**Comment by danharrin** [comment]
Is this solved by #6141? Can someone check please?

**Comment by Yo1L** [comment]
@danharrin I checked with v2.17.22. Sorry but It does not fix the issue.

**Comment by agentphoenix** [comment]
@danharrin Swapping the order of those operations does work for me.

**Comment by Yo1L** [comment]
@danharrin In my case, statePath is null in storeFileName.

**Comment by danharrin** [comment]
`storeFileName` is unrelated though in this case

**Comment by Yo1L** [comment]
@danharrin Ok :(
Wrong issue for me, the right one is #6143

**Comment by danharrin** [comment]
Fixed in #6141
