### ISSUE TITLE
Livewire persist issue after signing in

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#7072]
### Package

filament/filament

### Package Version

v3.0.0-beta3

### Laravel Version

v10.0.0

### PHP Version

8.2.4 

### Problem description

When login, dashboard not run 
i need to refresh the page to get dashboard

https://github.com/filamentphp/filament/assets/47450090/74850155-d225-4ade-840a-baa6bef52a7d

### Expected behavior

Run Normal witout refresh

### Steps to reproduce

Nothing

### Reproduction repository

https://github.com/mstfkhazaal/nscourse3

**Comment by zepfietje** [comment]
I can confirm this happens on the demo as well.
Getting `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'old._x_wasPersisted = true')` in the console after signing in.

Seems to be an issue with Livewire's persist feature.

**Comment by akunbeben** [comment]
> @akunbeben yeah the merge failed and we end up with duplicates filenames with different cases. We will be tagging a release soon that fixes that so you don't need to change your mac volumes 😅

I think [this](https://github.com/livewire/livewire/discussions/5775#discussioncomment-6503836) is related to this issue, it is solved now on Mac, but some Windows users still got a similar issue.

**Comment by zepfietje** [comment]
Seems unrelated to me, @akunbeben.
Still occurs on the latest Livewire beta.

**Comment by danharrin** [comment]
Removed `wire:navigate` until its more stable
