### ISSUE TITLE
Disappearing footer widgets on a dashboard page

### ISSUE THREAD

**Issue by alexjustesen** [laravel-filament/filament#8300]
### Package

filament/filament

### Package Version

v3.0.39

### Laravel Version

v10.22.0

### Livewire Version

v3.0.1

### PHP Version

PHP 8.2

### Problem description

1. On a page that has footer widgets (1 or more): the first widget will be dropped from the view and disappear when an action button is clicked.
2. On a page that has footer widgets (1 or more): the first widget will be dropped from the view and disappear after a few seconds when `wire:poll` is present in a page's view.
3. Worth noting this is not the case for any header widgets.

#### From action button click

https://github.com/filamentphp/filament/assets/1144087/dce7d61a-b040-4a5a-9217-24aacbcb676b

#### From wire poll in page

https://github.com/filamentphp/filament/assets/1144087/d49e4d8f-cf5d-401a-9269-da8e4c2bac01

### Expected behavior

Widgets should remain rendered on the page.

### Steps to reproduce

1. Fresh Laravel install
4. Fresh Filament install
5. Create a custom Dashboard page following the docs
6. Add more than one widget to `getFooterWidgets()`

### Reproduction repository

* Fresh repo: https://github.com/alexjustesen/filament-houdini-widgets
* First noticed it: https://github.com/alexjustesen/speedtest-tracker/pull/736

### Relevant log output

```shell
n/a
```

**Comment by alexjustesen** [comment]
Past related issues: #7567 and #8052

**Comment by alexjustesen** [comment]
Added https://github.com/alexjustesen/filament-houdini-widgets to track issues in a fresh repo and added better videos to show it happening.

**Comment by zepfietje** [comment]
Is this still an issue in the latest version of Livewire?

**Comment by alexjustesen** [comment]
> Is this still an issue in the latest version of Livewire?

Give me a day or so to update the repo and test again.

**Comment by zepfietje** [comment]
Sure, no rush, @alexjustesen!

**Comment by ImJustToNy** [comment]
Having same issue on Livewire 3.0.5, Filament 3.0.62, PHP 8.2.10, Laravel 10.24

**Comment by zepfietje** [comment]
Okay, thanks for confirming, @ImJustToNy.

**Comment by alexjustesen** [comment]
@zepfietje repo updated with the latest versions of the dependencies. Issues still exist.

**Comment by sawirricardo** [comment]
I confirm this issue still exists

**Comment by alexjustesen** [comment]
Updated with the latest dependencies, confirmed still an issue.

**Comment by danharrin** [comment]
Fixed by #10054.

**Comment by ImJustToNy** [comment]
> Fixed by #10054.

Thank you!

**Comment by ImJustToNy** [comment]
> Fixed by #10054.

~~It fixed the issue in some places, but it still persists in others.

From my understanding issue appears when both Header and Footer widgets are declared.

Minimal reproduction code in my case is:
```php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;

class ListUsers  extends ListRecords
{
    protected static string $resource = UserResource::class;

    protected function getHeaderWidgets(): array
    {
        return [
            UserResource\Widgets\HeaderWidget::class,
        ];
    }

    protected function getFooterWidgets(): array
    {
        return [
            UserResource\Widgets\FooterWidget::class,
        ];
    }
}
```

```php
namespace App\Filament\Resources\UserResource\Widgets;

use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class HeaderWidget extends BaseWidget
{
    protected function getStats(): array
    {
        return [
            //
        ];
    }
}
```

```php
namespace App\Filament\Resources\UserResource\Widgets;

use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class FooterWidget extends BaseWidget
{
    protected function getStats(): array
    {
        return [
            //
        ];
    }
}
```

@danharrin ~~

**Comment by danharrin** [comment]
I cannot reproduce, please create a new repository

**Comment by ImJustToNy** [comment]
> I cannot reproduce, please create a new repository

My bad, checked it on the wrong branch, everything works perfectly now :sweat_smile:. Thank you.
