### ISSUE TITLE
Color picker always send request and in --simple it's hard to choose

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#8614]
### Package

filament/filament

### Package Version

v3.0.53

### Laravel Version

v10.24.0

### Livewire Version

v3.0.5

### PHP Version

8.2

### Problem description

Color picker always send request whenever color is change, and in model `--simple` we cannot clearly select the color.
```php
// this is the only code that always send request to server
Forms\Components\ColorPicker::make('color')
```
You can cleary see from video
[Screencast from 09-20-2023 02:49:10 PM.webm](https://github.com/filamentphp/filament/assets/28250303/6dc929cb-a804-4b3a-ba96-84ef7fb1ff08)

### Expected behavior

1. Don't send request unless `->live()` is enable
2. In model, better selectable

### Steps to reproduce

1. Clone, install, login using `admin@example.com` and `password` credentials
2. Go to user resource, add new user and inspect 'network'
3. Go to color resource, open modal and click

### Reproduction repository

https://github.com/valpuia/color-bug

**Comment by zepfietje** [comment]
@danharrin, in non-Filament projects I've found that `$wire.$entangle('foo')` is live, and you have to explicitly set `live` to `false` using `$wire.$entangle('foo', false)`. It looks like this is a bug, as according to the Livewire docs `live` should be `false` by default. Not sure if this is the same issue, but just commenting for context.

**Comment by zepfietje** [comment]
@valpuia, I've confirmed with Dan that this is a Livewire bug. He's working on a PR to Livewire and will implement a fix in Filament for the time being.

**Comment by zepfietje** [comment]
Fixed in the latest release.

**Comment by valpuia** [comment]
> Fixed in the latest release.

Hi, Yes it's fixed for request send to server, but picker auto close in modal (--simple) is still not fix.. Do I need to create another issues for auto close color picker in modal?

**Comment by zepfietje** [comment]
Yes please, @valpuia.
